[build]
builder = "nixpacks"
buildCommand = "npm install --ignore-scripts && npx prisma generate && npx prisma migrate deploy && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
PORT = "3000"

# Force npm usage and bypass pnpm restrictions
[nixpacks]
providers = ["node"]

[nixpacks.variables]
NPM_CONFIG_PACKAGE_MANAGER = "npm"
NIXPACKS_NO_CACHE = "1"
NPM_CONFIG_IGNORE_SCRIPTS = "true"
