[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PNPM_VERSION = "10.7.0"

[environments.production.build]
buildCommand = "pnpm install --frozen-lockfile && pnpm prisma generate && pnpm build"
startCommand = "pnpm prisma migrate deploy && pnpm start"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[environments.staging.build]
buildCommand = "pnpm install --frozen-lockfile && pnpm prisma generate && pnpm build"
startCommand = "pnpm prisma migrate deploy && pnpm start"
