[build]
# Use Railway's auto-detection instead of Dockerfile
# builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Build configuration for auto-detection
[build.env]
# These will be available during build
DATABASE_URL = "postgresql://dummy:dummy@dummy:5432/dummy"
NEXTAUTH_SECRET = "dummy-secret-for-build"
NEXTAUTH_URL = "http://localhost:3000"
